name: Trigger Add to Personal Project

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

jobs:
  add-to-personal-project:
    uses: markheydon/github-workflows/.github/workflows/add-to-personal-project.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
